// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:animexhub/models/ani_pic.dart';
import 'package:animexhub/models/settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AniPicAdapter());
    registerAdapter(ModeAdapter());
    registerAdapter(RatingAdapter());
    registerAdapter(SettingsAdapter());
  }
}
